language: julia
julia:
  - 1.2

codecov: true

script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'

  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg;
                     cd(Pkg.dir("Cloudy"));
                     Pkg.add("Coverage");
                     using Coverage;
                     Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - export DOCUMENTER_DEBUG="true"
        - julia --color=yes --project=docs/ -e 'using Pkg;
                                                      Pkg.develop(PackageSpec(path=pwd()));
                                                      Pkg.instantiate();
                                                      Pkg.build("Cloudy")'
        - julia --color=yes --project=docs/ docs/make.jl
