language: julia
julia:
  - 1.2

codecov: true

script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'
